# app/config/services.yml
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
#    intl.twig.extension:
#        class: Twig_Extensions_Extension_Intl
#        tags:
#            - { name: twig.extension }